const FRIENDS_LIST = [
    {
        id: 1,
        email: "george.bluth@gmail.com",
        first_name: "George",
        last_name: "Bluth",
        avatar: "https://reqres.in/img/faces/1-image.jpg",
        city:"Thrissur", 
        age:20,
        state:"Kerala",
        country: "India",
        continent:"Asia",

        },
        {
        id: 2,
        email: "janet.weaver@gmail.com",
        first_name: "Janet",
        last_name: "Weaver",
        avatar: "https://reqres.in/img/faces/2-image.jpg",
        city:"Thrissur", 
        age:30,
        state:"Kerala",
        country: "India",
        continent:"Asia",
        },
        {
        id: 3,
        email: "emma.wong@gmail.com",
        first_name: "Emma",
        last_name: "Wong",
        avatar: "https://reqres.in/img/faces/3-image.jpg",
        city:"Thrissur", 
        age:26,
        state:"Kerala",
        country: "India",
        continent:"Asia",
        },
        {
        id: 4,
        email: "eve.holt@gmail.com",
        first_name: "Eve",
        last_name: "Holt",
        avatar: "https://reqres.in/img/faces/4-image.jpg",
        city:"Thrissur", 
        age:29,
        state:"Kerala",
        country: "India",
        continent:"Asia",
        },
        {
        id: 5,
        email: "charles.morris@gmail.com",
        first_name: "Charles",
        last_name: "Morris",
        avatar: "https://reqres.in/img/faces/5-image.jpg",
        city:"Thrissur", 
        age:47,
        state:"Kerala",
        country: "India",
        continent:"Asia",
        },
        {
        id: 6,
        email: "tracey.ramos@gmail.com",
        first_name: "Tracey",
        last_name: "Ramos",
        avatar: "https://reqres.in/img/faces/6-image.jpg",
        city:"Thrissur", 
        age:90,
        state:"Kerala",
        country: "India",
        continent:"Asia",
        },
        {
            id: 7,
            email: "soman@gmail.com",
            first_name: "soman",
            last_name: "Ramos",
            avatar: "https://reqres.in/img/faces/1-image.jpg",
            city:"Thrissur", 
            age:28,
            state:"Kerala",
            country: "India",
            continent:"Asia",
            },
            {
        id: 8,
        email: "alfred@gmail.com",
        first_name: "alfred",
        last_name: "roshan",
        avatar: "https://reqres.in/img/faces/3-image.jpg",
        city:"Thrissur", 
        age:70,
        state:"Kerala",
        country: "India",
        continent:"Asia",
        },
        {
            id: 9,
            email: "geon@gmail.com",
            first_name: "geon",
            last_name: "koni",
            avatar: "https://reqres.in/img/faces/2-image.jpg",
            city:"Thrissur", 
            age:29,
            state:"Kerala",
            country: "India",
            continent:"Asia",
            },
            {
                id: 10,
                email: "akshay@gmail.com",
                first_name: "akshay",
                last_name: "ravi",
                avatar: "https://reqres.in/img/faces/4-image.jpg",
                city:"Thrissur", 
                age:20,
                state:"Kerala",
                country: "India",
                continent:"Asia",
                },
                {
                    id: 11,
                    email: "aswathy@gmail.com",
                    first_name: "aswathy",
                    last_name: "Ram",
                    avatar: "https://reqres.in/img/faces/1-image.jpg",
                    city:"Thrissur", 
                    age:10,
                    state:"Kerala",
                    country: "India",
                    continent:"Asia",
                    },
                    {
                        id: 12,
                        email: "akhil@gmail.com",
                        first_name: "akihl",
                        last_name: "shaji",
                        avatar: "https://reqres.in/img/faces/6-image.jpg",
                        city:"Thrissur", 
                        age:20,
                        state:"Kerala",
                        country: "India",
                        continent:"Asia",
                        },
                        {
                            id: 13,
                            email: "aiswarya@gmail.com",
                            first_name: "aiswarya",
                            last_name: "ajith",
                            avatar: "https://reqres.in/img/faces/5-image.jpg",
                            city:"Thrissur", 
                            age:50,
                            state:"Kerala",
                            country: "India",
                            continent:"Asia",
                            },
                            {
                                id: 14,
                                email: "virat@gmail.com",
                                first_name: "virat",
                                last_name: "kohli",
                                avatar: "https://reqres.in/img/faces/1-image.jpg",
                                city:"Thrissur", 
                                age:34,
                                state:"Kerala",
                                country: "India",
                                continent:"Asia",
                                }
];
export default FRIENDS_LIST;